spring:
  profiles:
    active: test
  application:
    name: goods_catalogue_service
server:
  port: 8000
kafka:
  configuration:
    bootstrapServers: localhost:9092
    recomendations:
      sampling: 100
      topic: recomendations-topic
services:
  recomendations:
    url: http://localhost:8001
management:
  endpoints:
    web:
      exposure:
        include: beans
goods:
  page:
    size: 30
  fallback:
    categories_size: 7